name = "TidEscape"
prd = "./instruction.md"

[game]
tags = ["raylib", "2D", "c"]
screenshots = ["./screenshots/screen-01.png"]
videos = ["https://www.internalfb.com/intern/px/p/bd8gT"]  # upload to bunnylol px, link here
teaser = "https://www.internalfb.com/intern/px/p/bd8gT"  # 7 sec highlight video, px link

[binaries]
# Archive (zip) binaries before referencing them here
osx = "./binaries/game.app.zip"
